name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      # Use Xcode 15.4 explicitly
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Check versions
        run: |
          xcodebuild -version
          swift --version

      # Temporarily downgrade Swift version in Package.swift files
      - name: Update Swift version in packages
        run: |
          find . -name "Package.swift" -type f -exec sed -i '' '1s/swift-tools-version:6.0.0/swift-tools-version:5.10.0/' {} +
          
          # Show all Package.swift versions
          echo "Modified Package.swift files:"
          find . -name "Package.swift" -type f -exec head -n 1 {} \;

      - name: Clean
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/.build

      - name: Build App
        run: |
          xcodebuild -scheme madari -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create DMG
        run: |
          mkdir -p /tmp/dmg
          cp -r "build/Release/madari.app" /tmp/dmg/
          hdiutil create -volname "madari" \
            -srcfolder /tmp/dmg \
            -ov \
            -format UDZO \
            "madari.dmg"
          rm -rf /tmp/dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: madari
          path: madari.dmg
